-- Selecione o banco criado pela Hostinger antes de importar este arquivo.
-- Este script nao cria nem troca de banco de dados.

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  request_id CHAR(36) NOT NULL,
  form_type VARCHAR(40) NOT NULL,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(180) NULL,
  phone VARCHAR(40) NOT NULL,
  document VARCHAR(40) NULL,
  dealership_unit VARCHAR(120) NULL,
  state VARCHAR(80) NULL,
  city VARCHAR(120) NULL,
  model VARCHAR(160) NULL,
  department VARCHAR(120) NULL,
  service_type VARCHAR(120) NULL,
  preferred_date DATE NULL,
  preferred_time VARCHAR(20) NULL,
  message TEXT NULL,
  page_url VARCHAR(500) NULL,
  utm_source VARCHAR(120) NULL,
  utm_medium VARCHAR(120) NULL,
  utm_campaign VARCHAR(180) NULL,
  utm_term VARCHAR(180) NULL,
  utm_content VARCHAR(180) NULL,
  gclid VARCHAR(255) NULL,
  fbclid VARCHAR(255) NULL,
  lgpd_consent TINYINT(1) NOT NULL DEFAULT 0,
  ip_address VARBINARY(16) NULL,
  user_agent VARCHAR(500) NULL,
  crm_status ENUM('pending', 'sent', 'failed', 'disabled') NOT NULL DEFAULT 'pending',
  crm_response JSON NULL,
  crm_sent_at DATETIME NULL,
  email_status ENUM('pending', 'sent', 'failed', 'disabled') NOT NULL DEFAULT 'pending',
  email_recipient VARCHAR(180) NULL,
  email_provider_id VARCHAR(100) NULL,
  email_response JSON NULL,
  email_sent_at DATETIME NULL,
  raw_payload JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_leads_public_id (public_id),
  UNIQUE KEY uq_leads_request_id (request_id),
  KEY idx_leads_created_at (created_at),
  KEY idx_leads_form_type (form_type),
  KEY idx_leads_crm_status (crm_status),
  KEY idx_leads_email_status (email_status),
  KEY idx_leads_phone (phone),
  KEY idx_leads_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
